# Generated by Django 2.1 on 2018-12-31 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='patientstest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient'),
        ),
        migrations.AddField(
            model_name='patientstest',
            name='testType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TestType'),
        ),
    ]
