# Generated by Django 2.1 on 2019-01-04 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181231_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodCountTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hb', models.FloatField()),
                ('rbc', models.FloatField()),
                ('hct', models.FloatField()),
                ('wbc', models.FloatField()),
                ('patientsTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PatientsTest')),
            ],
        ),
    ]
